# app/services/form_generator.rb
class FormGenerator
  attr_reader :form_template, :errors
  
  def initialize(form_template)
    @form_template = form_template
    @errors = []
  end
  
  def generate!
    return false unless validate_template
    
    begin
      generate_model
      generate_migration
      generate_controller
      generate_view
      add_route
      add_sidebar_link
      
      true
    rescue => e
      @errors << "Generation failed: #{e.message}"
      Rails.logger.error("Form generation error: #{e.message}")
      Rails.logger.error(e.backtrace.join("\n"))
      false
    end
  end
  
  private
  
  def validate_template
    if form_template.form_fields.empty?
      @errors << "Form must have at least one field"
      return false
    end
    
    true
  end
  
  def generate_model
    model_path = Rails.root.join("app/models/#{form_template.file_name}.rb")
    
    # Build field definitions for migration
    field_definitions = form_template.form_fields.map do |field|
      case field.field_type
      when 'text', 'dropdown'
        "  # #{field.label}\n  attribute :#{field.field_name}, :string"
      when 'text_box'
        "  # #{field.label}\n  attribute :#{field.field_name}, :text"
      end
    end.join("\n")
    
    content = <<~RUBY
      # Generated by Paperboy Form Builder
      # Form Template ID: #{form_template.id}
      # Access: #{form_template.access_level}
      #{form_template.restricted? ? "# ACL Group: #{form_template.acl_group_name} (ID: #{form_template.acl_group_id})" : ""}
      
      class #{form_template.class_name} < ApplicationRecord
        # Form fields
      #{field_definitions}
        
        # Validations
      #{generate_validations}
        
        # Access control
        def self.accessible_by?(employee_id)
          #{generate_access_check}
        end
        
        # Page information
        def self.page_count
          #{form_template.page_count}
        end
        
        def self.page_header(page_num)
          headers = #{form_template.page_headers.to_s}
          
          case page_num
          when 1
            "Employee Info"
          when 2
            "Agency Info"
          else
            headers[page_num - 3] || "Page \#{page_num}"
          end
        end
      end
    RUBY
    
    File.write(model_path, content)
  end
  
  def generate_migration
    timestamp = Time.now.utc.strftime("%Y%m%d%H%M%S")
    migration_path = Rails.root.join("db/migrate/#{timestamp}_create_#{form_template.table_name}.rb")
    
    # Build column definitions
    columns = form_template.form_fields.map do |field|
      case field.field_type
      when 'text', 'dropdown'
        "      t.string :#{field.field_name}"
      when 'text_box'
        "      t.text :#{field.field_name}"
      end
    end.join("\n")
    
    content = <<~RUBY
      # Generated by Paperboy Form Builder
      class Create#{form_template.class_name.pluralize} < ActiveRecord::Migration[7.1]
        def change
          create_table :#{form_template.table_name} do |t|
            # Standard fields
            t.integer :employee_id
            t.string :status, default: 'draft'
            
            # Form fields
      #{columns}
            
            t.timestamps
          end
          
          add_index :#{form_template.table_name}, :employee_id
          add_index :#{form_template.table_name}, :status
        end
      end
    RUBY
    
    File.write(migration_path, content)
  end
  
  def generate_controller
    controller_path = Rails.root.join("app/controllers/#{form_template.plural_file_name}_controller.rb")
    
    content = <<~RUBY
      # Generated by Paperboy Form Builder
      class #{form_template.class_name.pluralize}Controller < ApplicationController
        before_action :check_access
        before_action :set_#{form_template.file_name}, only: [:show, :edit, :update, :destroy]
        
        def index
          @#{form_template.plural_file_name} = #{form_template.class_name}.where(
            employee_id: session.dig(:user, "employee_id")
          ).order(created_at: :desc)
        end
        
        def new
          @#{form_template.file_name} = #{form_template.class_name}.new
          @current_page = (params[:page] || 1).to_i
        end
        
        def create
          @#{form_template.file_name} = #{form_template.class_name}.new(#{form_template.file_name}_params)
          @#{form_template.file_name}.employee_id = session.dig(:user, "employee_id")
          
          if @#{form_template.file_name}.save
            redirect_to #{form_template.plural_file_name}_path, notice: 'Form submitted successfully.'
          else
            @current_page = (params[:page] || 1).to_i
            render :new
          end
        end
        
        def show
        end
        
        def edit
          @current_page = (params[:page] || 1).to_i
        end
        
        def update
          if @#{form_template.file_name}.update(#{form_template.file_name}_params)
            redirect_to @#{form_template.file_name}, notice: 'Form updated successfully.'
          else
            @current_page = (params[:page] || 1).to_i
            render :edit
          end
        end
        
        def destroy
          @#{form_template.file_name}.destroy
          redirect_to #{form_template.plural_file_name}_path, notice: 'Form deleted successfully.'
        end
        
        private
        
        def set_#{form_template.file_name}
          @#{form_template.file_name} = #{form_template.class_name}.find(params[:id])
        end
        
        def #{form_template.file_name}_params
          params.require(:#{form_template.file_name}).permit(
            #{generate_permitted_params}
          )
        end
        
        def check_access
          employee_id = session.dig(:user, "employee_id")
          
          unless #{form_template.class_name}.accessible_by?(employee_id)
            redirect_to root_path, alert: "Access denied."
          end
        end
      end
    RUBY
    
    File.write(controller_path, content)
  end
  
  def generate_view
    view_dir = Rails.root.join("app/views/#{form_template.plural_file_name}")
    FileUtils.mkdir_p(view_dir)
    
    # Generate new.html.erb with multi-page support
    view_path = view_dir.join("new.html.erb")
    
    content = generate_view_content
    
    File.write(view_path, content)
  end
  
  def generate_view_content
    pages_content = (1..form_template.page_count).map do |page_num|
      fields_for_page = form_template.form_fields.for_page(page_num)
      next if fields_for_page.empty?
      
      fields_html = fields_for_page.map { |field| generate_field_html(field) }.join("\n    ")
      
      <<~HTML
        <% if @current_page == #{page_num} %>
          <div class="form-page">
            <h2>#{form_template.page_header(page_num)}</h2>
            
            #{fields_html}
            
            <div class="form-navigation">
              <% if @current_page > 1 %>
                <%= link_to "← Previous", new_#{form_template.file_name}_path(page: @current_page - 1), class: "btn btn-secondary" %>
              <% end %>
              
              <% if @current_page < #{form_template.page_count} %>
                <%= link_to "Next →", new_#{form_template.file_name}_path(page: @current_page + 1), class: "btn btn-primary" %>
              <% else %>
                <%= f.submit "Submit Form", class: "btn btn-success" %>
              <% end %>
            </div>
          </div>
        <% end %>
      HTML
    end.join("\n")
    
    <<~HTML
      <!-- Generated by Paperboy Form Builder -->
      <div class="form-container">
        <h1><%= "#{form_template.name}" %></h1>
        
        <!-- Page Progress -->
        <div class="page-progress">
          <% (1..#{form_template.page_count}).each do |page| %>
            <span class="<%= @current_page == page ? 'active' : '' %>">
              Page <%= page %> of #{form_template.page_count}
            </span>
          <% end %>
        </div>
        
        <%= form_with model: @#{form_template.file_name}, 
                      url: #{form_template.plural_file_name}_path,
                      local: true do |f| %>
          
          <%= hidden_field_tag :page, @current_page %>
          
          #{pages_content}
          
        <% end %>
      </div>
    HTML
  end
  
  def generate_field_html(field)
    case field.field_type
    when 'text'
      <<~HTML
        <div class="form-group">
          <%= f.label :#{field.field_name}, "#{field.label}" %>
          <%= f.text_field :#{field.field_name}, class: "form-control"#{field.required ? ', required: true' : ''} %>
        </div>
      HTML
    when 'text_box'
      <<~HTML
        <div class="form-group">
          <%= f.label :#{field.field_name}, "#{field.label}" %>
          <%= f.text_area :#{field.field_name}, rows: #{field.rows}, class: "form-control"#{field.required ? ', required: true' : ''} %>
        </div>
      HTML
    when 'dropdown'
      values = field.dropdown_values.map { |v| "'#{v}'" }.join(', ')
      <<~HTML
        <div class="form-group">
          <%= f.label :#{field.field_name}, "#{field.label}" %>
          <%= f.select :#{field.field_name}, 
                      options_for_select([#{values}]),
                      { include_blank: "Select..." },
                      { class: "form-control"#{field.required ? ', required: true' : ''} } %>
        </div>
      HTML
    end
  end
  
  def generate_validations
    validations = form_template.form_fields.select(&:required).map do |field|
      "  validates :#{field.field_name}, presence: true"
    end.join("\n")
    
    validations.presence || "  # No required fields"
  end
  
  def generate_access_check
    if form_template.restricted?
      <<~RUBY
        return false unless employee_id
            
            result = ActiveRecord::Base.connection.execute(
              "SELECT COUNT(*) as count 
               FROM GSABSS.dbo.GroupMembers 
               WHERE EmployeeID = \#{employee_id} 
               AND GroupID = #{form_template.acl_group_id}"
            ).first
            
            result && result['count'].to_i > 0
          rescue
            false
      RUBY
    else
      "true  # Public access"
    end
  end
  
  def generate_permitted_params
    field_names = form_template.form_fields.map { |f| ":#{f.field_name}" }
    field_names.join(",\n            ")
  end
  
  def add_route
    routes_path = Rails.root.join("config/routes.rb")
    routes_content = File.read(routes_path)
    
    route_line = "  resources :#{form_template.plural_file_name}\n"
    
    # Check if route already exists
    return if routes_content.include?(route_line.strip)
    
    # Insert before the last 'end'
    updated_content = routes_content.sub(/\nend\z/, "\n#{route_line}end")
    File.write(routes_path, updated_content)
  end
  
  def add_sidebar_link
    sidebar_path = Rails.root.join("app/views/shared/_sidebar.html.erb")
    return unless File.exist?(sidebar_path)
    
    sidebar_content = File.read(sidebar_path)
    
    label = form_template.name
    helper = "new_#{form_template.file_name}_path"
    line = %(      ["#{label}", #{helper}],\n)
    
    # Check if link already exists
    return if sidebar_content.include?(line.strip)
    
    # Insert before the closing bracket of the forms array
    updated_content = sidebar_content.sub(/^\s*\]\s*%>/, "#{line}    ] %>")
    File.write(sidebar_path, updated_content)
  end
end
