# frozen_string_literal: true

[
  'BscreatesSales',
  {
    steps: {
      enabled: false,
      manual_steps: Workflow::MANUAL_STEPS,
      scheduled: {
        frequency: :daily,
        steps: Workflow::SCHEDULED_STEPS
      }
    },
    group: {
      name: 'billing_configuration'
    },
    source: {
      location: '/mnt/i/BUSINESS_SUPPORT/DataRunner/01_Download/bscreates_sales.csv',
      local: 'bscreates_sales.csv',
      format: :csv,
      strategy: :copy
    },
    to_csv: {
      sheet: 0,
      header_row: 0,
      data_row: 1
    },
    header: [

      ['order_id',                 'order_id',                 'nvarchar(max)', 'NULL', nil],
      ['order_name',               'order_name',               'nvarchar(max)', 'NULL', nil],
      ['order_status',             'order_status',             'nvarchar(max)', 'NULL', nil],
      ['created_date',             'created_date',             'nvarchar(max)', 'NULL', nil],
      ['order_submitted',          'order_submitted',          'nvarchar(max)', 'NULL', nil],
      ['production_received_date', 'production_received_date', 'nvarchar(max)', 'NULL', nil],
      ['field_removed',            'field_removed',            'nvarchar(max)', 'NULL', nil],
      ['completed',                'completed',                'nvarchar(max)', 'NULL', nil],
      ['requested',                'requested',                'nvarchar(max)', 'NULL', nil],
      ['due',                      'due',                      'nvarchar(max)', 'NULL', nil],
      ['user_id',                  'user_id',                  'nvarchar(max)', 'NULL', nil],
      ['user_domain',              'user_domain',              'nvarchar(max)', 'NULL', nil],
      ['customer',                 'customer',                 'nvarchar(max)', 'NULL', nil],
      ['location',                 'location',                 'nvarchar(max)', 'NULL', nil],
      ['company',                  'company',                  'nvarchar(max)', 'NULL', nil],
      ['department',               'department',               'nvarchar(max)', 'NULL', nil],
      ['skin',                     'skin',                     'nvarchar(max)', 'NULL', nil],
      ['ordered_on_behalf',        'ordered_on_behalf',        'nvarchar(max)', 'NULL', nil],
      ['order_placer',             'order_placer',             'nvarchar(max)', 'NULL', nil],
      ['order_placer_domain',      'order_placer_domain',      'nvarchar(max)', 'NULL', nil],
      ['approver',                 'approver',                 'nvarchar(max)', 'NULL', nil],
      ['approval_datetime',        'approval_datetime',        'nvarchar(max)', 'NULL', nil],
      ['approval_action',          'approval_action',          'nvarchar(max)', 'NULL', nil],
      ['activity',                 'activity',                 'nvarchar(max)', 'NULL', nil],
      ['budget_unit',              'budget_unit',              'nvarchar(max)', 'NULL', nil],
      ['function',                 'function',                 'nvarchar(max)', 'NULL', nil],
      ['program',                  'program',                  'nvarchar(max)', 'NULL', nil],
      ['paid_by',                  'paid_by',                  'nvarchar(max)', 'NULL', nil],
      ['authorization_id',         'authorization_id',         'nvarchar(max)', 'NULL', nil],
      ['payment_state',            'payment_state',            'nvarchar(max)', 'NULL', nil],
      ['billing_last_name',        'billing_last_name',        'nvarchar(max)', 'NULL', nil],
      ['billing_first_name',       'billing_first_name',       'nvarchar(max)', 'NULL', nil],
      ['billing_middle_name',      'billing_middle_name',      'nvarchar(max)', 'NULL', nil],
      ['billing_company',          'billing_company',          'nvarchar(max)', 'NULL', nil],
      ['billing_location',         'billing_location',         'nvarchar(max)', 'NULL', nil],
      ['billing_job_title',        'billing_job_title',        'nvarchar(max)', 'NULL', nil],
      ['billing_email',            'billing_email',            'nvarchar(max)', 'NULL', nil],
      ['billing_address_1',        'billing_address_1',        'nvarchar(max)', 'NULL', nil],
      ['billing_address_2',        'billing_address_2',        'nvarchar(max)', 'NULL', nil],
      ['billing_address_3',        'billing_address_3',        'nvarchar(max)', 'NULL', nil],
      ['billing_city',             'billing_city',             'nvarchar(max)', 'NULL', nil],
      ['billing_state',            'billing_state',            'nvarchar(max)', 'NULL', nil],
      ['billing_zip',              'billing_zip',              'nvarchar(max)', 'NULL', nil],
      ['billing_country',          'billing_country',          'nvarchar(max)', 'NULL', nil],
      ['billing_phone_1',          'billing_phone_1',          'nvarchar(max)', 'NULL', nil],
      ['billing_phone_2',          'billing_phone_2',          'nvarchar(max)', 'NULL', nil],
      ['billing_phone_3',          'billing_phone_3',          'nvarchar(max)', 'NULL', nil],
      ['billing_fax',              'billing_fax',              'nvarchar(max)', 'NULL', nil],
      ['billing_url',              'billing_url',              'nvarchar(max)', 'NULL', nil],
      ['item_owner_user_id',       'item_owner_user_id',       'nvarchar(max)', 'NULL', nil],
      ['item_owner',               'item_owner',               'nvarchar(max)', 'NULL', nil],
      ['folder',                   'folder',                   'nvarchar(max)', 'NULL', nil],
      ['item',                     'item',                     'nvarchar(max)', 'NULL', nil],
      ['form_number',              'form_number',              'nvarchar(max)', 'NULL', nil],
      ['from_workgroup',           'from_workgroup',           'nvarchar(max)', 'NULL', nil],
      ['is_inventory_item',        'is_inventory_item',        'nvarchar(max)', 'NULL', nil],
      ['is_kit',                   'is_kit',                   'nvarchar(max)', 'NULL', nil],
      ['is_item_priced',           'is_item_priced',           'nvarchar(max)', 'NULL', nil],
      ['recipient',                'recipient',                'nvarchar(max)', 'NULL', nil],
      ['field_removed_2',          'field_removed_2',          'nvarchar(max)', 'NULL', nil],
      ['tracking_number',          'tracking_number',          'nvarchar(max)', 'NULL', nil],
      ['recipient_last_name',      'recipient_last_name',      'nvarchar(max)', 'NULL', nil],
      ['recipient_first_name',     'recipient_first_name',     'nvarchar(max)', 'NULL', nil],
      ['recipient_middle_name',    'recipient_middle_name',    'nvarchar(max)', 'NULL', nil],
      ['ship_company',             'ship_company',             'nvarchar(max)', 'NULL', nil],
      ['ship_location',            'ship_location',            'nvarchar(max)', 'NULL', nil],
      ['ship_job_title',           'ship_job_title',           'nvarchar(max)', 'NULL', nil],
      ['ship_email',               'ship_email',               'nvarchar(max)', 'NULL', nil],
      ['ship_address_addr_line_1', 'ship_address_addr_line_1', 'nvarchar(max)', 'NULL', nil],
      ['ship_address_addr_line_2', 'ship_address_addr_line_2', 'nvarchar(max)', 'NULL', nil],
      ['ship_address_addr_line_3', 'ship_address_addr_line_3', 'nvarchar(max)', 'NULL', nil],
      ['ship_city',                'ship_city',                'nvarchar(max)', 'NULL', nil],
      ['ship_state',               'ship_state',               'nvarchar(max)', 'NULL', nil],
      ['ship_zip',                 'ship_zip',                 'nvarchar(max)', 'NULL', nil],
      ['ship_country',             'ship_country',             'nvarchar(max)', 'NULL', nil],
      ['ship_phone_1',             'ship_phone_1',             'nvarchar(max)', 'NULL', nil],
      ['ship_phone_2',             'ship_phone_2',             'nvarchar(max)', 'NULL', nil],
      ['ship_phone_3',             'ship_phone_3',             'nvarchar(max)', 'NULL', nil],
      ['ship_fax',                 'ship_fax',                 'nvarchar(max)', 'NULL', nil],
      ['ship_url',                 'ship_url',                 'nvarchar(max)', 'NULL', nil],
      ['cost_category',            'cost_category',            'nvarchar(max)', 'NULL', nil],
      ['cost_option',              'cost_option',              'nvarchar(max)', 'NULL', nil],
      ['unit_of_measure',          'unit_of_measure',          'nvarchar(max)', 'NULL', nil],
      ['units_per_copy',           'units_per_copy',           'nvarchar(max)', 'NULL', nil],
      ['priced_copies',            'priced_copies',            'nvarchar(max)', 'NULL', nil],
      ['priced_units',             'priced_units',             'nvarchar(max)', 'NULL', nil],
      ['unit_price',               'unit_price',               'nvarchar(max)', 'NULL', nil],
      ['total_price',              'total_price',              'nvarchar(max)', 'NULL', nil],
      ['order_original_site',      'order_original_site',      'nvarchar(max)', 'NULL', nil],
      ['field_removed_3',          'field_removed_3',          'nvarchar(max)', 'NULL', nil],
      ['order_site_email',         'order_site_email',         'nvarchar(max)', 'NULL', nil],
      ['order_site_address_1',     'order_site_address_1',     'nvarchar(max)', 'NULL', nil],
      ['order_site_address_2',     'order_site_address_2',     'nvarchar(max)', 'NULL', nil],
      ['order_site_address_3',     'order_site_address_3',     'nvarchar(max)', 'NULL', nil],
      ['order_site_city',          'order_site_city',          'nvarchar(max)', 'NULL', nil],
      ['order_site_state',         'order_site_state',         'nvarchar(max)', 'NULL', nil],
      ['order_site_zip',           'order_site_zip',           'nvarchar(max)', 'NULL', nil],
      ['order_site_country',       'order_site_country',       'nvarchar(max)', 'NULL', nil],
      ['order_site_phone_1',       'order_site_phone_1',       'nvarchar(max)', 'NULL', nil],
      ['order_site_url',           'order_site_url',           'nvarchar(max)', 'NULL', nil],
      ['total_items',              'total_items',              'nvarchar(max)', 'NULL', nil],
      ['total_quantity',           'total_quantity',           'nvarchar(max)', 'NULL', nil],
      ['total_pdf_pages',          'total_pdf_pages',          'nvarchar(max)', 'NULL', nil],
      ['total_cost',               'total_cost',               'nvarchar(max)', 'NULL', nil],
      ['approval_cost_estimate',   'approval_cost_estimate',   'nvarchar(max)', 'NULL', nil],
      ['ordering_cost_estimate',   'ordering_cost_estimate',   'nvarchar(max)', 'NULL', nil],
      ['billing_department',       'billing_department',       'nvarchar(max)', 'NULL', nil],
      ['activity_split',           'activity_split',           'nvarchar(max)', 'NULL', nil],
      ['budget_unit_split',        'budget_unit_split',        'nvarchar(max)', 'NULL', nil],
      ['function_split',           'function_split',           'nvarchar(max)', 'NULL', nil],
      ['program_split',            'program_split',            'nvarchar(max)', 'NULL', nil],
      ['activity_total_split',     'activity_total_split',     'nvarchar(max)', 'NULL', nil],
      ['budget_unit_total_split',  'budget_unit_total_split',  'nvarchar(max)', 'NULL', nil],
      ['function_total_split',     'function_total_split',     'nvarchar(max)', 'NULL', nil],
      ['program_total_split',      'program_total_split',      'nvarchar(max)', 'NULL', nil],
      ['approval_group_name',      'approval_group_name',      'nvarchar(max)', 'NULL', nil],
      ['total_color_impressions',  'total_color_impressions',  'nvarchar(max)', 'NULL', nil],
      ['total_bw_impressions',     'total_bw_impressions',     'nvarchar(max)', 'NULL', nil],
      ['entitlement',              'entitlement',              'nvarchar(max)', 'NULL', nil],
      ['price_card',               'price_card',               'nvarchar(max)', 'NULL', nil],
      ['item_2',                   'item_2',                   'nvarchar(max)', 'NULL', nil],
      ['recipient_2',              'recipient_2',              'nvarchar(max)', 'NULL', nil]

    ],
    database_connections: [
      {
        host: 'GSASQL16',
        database: 'GSABSS',
        schema: 'dbo',
        table: 'bscreates_sales',
        inject: {
          mode: :truncate_insert
        }
      }
    ]
  }
]
