# frozen_string_literal: true

[
  'Fedex',
  {
    steps: {
      enabled: false,
      manual_steps: Workflow::MANUAL_STEPS,
      scheduled: {
        frequency: :daily,
        steps: Workflow::SCHEDULED_STEPS
      }
    },
    group: {
      name: 'mail_center_and_warehousing'
    },
    source: {
      location: '/mnt/i/BUSINESS_SUPPORT/DataRunner/01_Download/fedex.xlsx',
      local: 'fedex.xlsx',
      format: :xlsx,
      strategy: :copy
    },
    to_csv: {
      sheet: 0,
      header_row: 0,
      data_row: 1
    },
    header: [

      [ 'consolidated_account_number',                                  'consolidated_account_number',                                  'nvarchar(max)', 'NULL', nil ],
      [ 'bill_to_account_number',                                       'bill_to_account_number',                                       'nvarchar(max)', 'NULL', nil ],
      [ 'invoice_date',                                                 'invoice_date',                                                 'nvarchar(max)', 'NULL', nil ],
      [ 'invoice_number',                                               'invoice_number',                                               'nvarchar(max)', 'NULL', nil ],
      [ 'store_id',                                                     'store_id',                                                     'nvarchar(max)', 'NULL', nil ],
      [ 'original_amount_due',                                          'original_amount_due',                                          'nvarchar(max)', 'NULL', nil ],
      [ 'current_balance',                                              'current_balance',                                              'nvarchar(max)', 'NULL', nil ],
      [ 'payor',                                                        'payor',                                                        'nvarchar(max)', 'NULL', nil ],
      [ 'ground_tracking_id_prefix',                                    'ground_tracking_id_prefix',                                    'nvarchar(max)', 'NULL', nil ],
      [ 'express_or_ground_tracking_id',                                'express_or_ground_tracking_id',                                'nvarchar(max)', 'NULL', nil ],
      [ 'transportation_charge_amount',                                 'transportation_charge_amount',                                 'nvarchar(max)', 'NULL', nil ],
      [ 'net_charge_amount',                                            'net_charge_amount',                                            'nvarchar(max)', 'NULL', nil ],
      [ 'service_type',                                                 'service_type',                                                 'nvarchar(max)', 'NULL', nil ],
      [ 'ground_service',                                               'ground_service',                                               'nvarchar(max)', 'NULL', nil ],
      [ 'shipment_date',                                                'shipment_date',                                                'nvarchar(max)', 'NULL', nil ],
      [ 'pod_delivery_date',                                            'pod_delivery_date',                                            'nvarchar(max)', 'NULL', nil ],
      [ 'pod_delivery_time',                                            'pod_delivery_time',                                            'nvarchar(max)', 'NULL', nil ],
      [ 'pod_service_area_code',                                        'pod_service_area_code',                                        'nvarchar(max)', 'NULL', nil ],
      [ 'pod_signature_description',                                    'pod_signature_description',                                    'nvarchar(max)', 'NULL', nil ],
      [ 'actual_weight_amount',                                         'actual_weight_amount',                                         'nvarchar(max)', 'NULL', nil ],
      [ 'actual_weight_units',                                          'actual_weight_units',                                          'nvarchar(max)', 'NULL', nil ],
      [ 'rated_weight_amount',                                          'rated_weight_amount',                                          'nvarchar(max)', 'NULL', nil ],
      [ 'rated_weight_units',                                           'rated_weight_units',                                           'nvarchar(max)', 'NULL', nil ],
      [ 'number_of_pieces',                                             'number_of_pieces',                                             'nvarchar(max)', 'NULL', nil ],
      [ 'bundle_number',                                                'bundle_number',                                                'nvarchar(max)', 'NULL', nil ],
      [ 'meter_number',                                                 'meter_number',                                                 'nvarchar(max)', 'NULL', nil ],
      [ 'tdmastertrackingid',                                           'tdmastertrackingid',                                           'nvarchar(max)', 'NULL', nil ],
      [ 'service_packaging',                                            'service_packaging',                                            'nvarchar(max)', 'NULL', nil ],
      [ 'dim_length',                                                   'dim_length',                                                   'nvarchar(max)', 'NULL', nil ],
      [ 'dim_width',                                                    'dim_width',                                                    'nvarchar(max)', 'NULL', nil ],
      [ 'dim_height',                                                   'dim_height',                                                   'nvarchar(max)', 'NULL', nil ],
      [ 'dim_divisor',                                                  'dim_divisor',                                                  'nvarchar(max)', 'NULL', nil ],
      [ 'dim_unit',                                                     'dim_unit',                                                     'nvarchar(max)', 'NULL', nil ],
      [ 'recipient_name',                                               'recipient_name',                                               'nvarchar(max)', 'NULL', nil ],
      [ 'recipient_company',                                            'recipient_company',                                            'nvarchar(max)', 'NULL', nil ],
      [ 'recipient_address_line_1',                                     'recipient_address_line_1',                                     'nvarchar(max)', 'NULL', nil ],
      [ 'recipient_address_line_2',                                     'recipient_address_line_2',                                     'nvarchar(max)', 'NULL', nil ],
      [ 'recipient_city',                                               'recipient_city',                                               'nvarchar(max)', 'NULL', nil ],
      [ 'recipient_state',                                              'recipient_state',                                              'nvarchar(max)', 'NULL', nil ],
      [ 'recipient_zip_code',                                           'recipient_zip_code',                                           'nvarchar(max)', 'NULL', nil ],
      [ 'recipient_countryterritory',                                   'recipient_countryterritory',                                   'nvarchar(max)', 'NULL', nil ],
      [ 'shipper_company',                                              'shipper_company',                                              'nvarchar(max)', 'NULL', nil ],
      [ 'shipper_name',                                                 'shipper_name',                                                 'nvarchar(max)', 'NULL', nil ],
      [ 'shipper_address_line_1',                                       'shipper_address_line_1',                                       'nvarchar(max)', 'NULL', nil ],
      [ 'shipper_address_line_2',                                       'shipper_address_line_2',                                       'nvarchar(max)', 'NULL', nil ],
      [ 'shipper_city',                                                 'shipper_city',                                                 'nvarchar(max)', 'NULL', nil ],
      [ 'shipper_state',                                                'shipper_state',                                                'nvarchar(max)', 'NULL', nil ],
      [ 'shipper_zip_code',                                             'shipper_zip_code',                                             'nvarchar(max)', 'NULL', nil ],
      [ 'shipper_countryterritory',                                     'shipper_countryterritory',                                     'nvarchar(max)', 'NULL', nil ],
      [ 'original_customer_reference',                                  'original_customer_reference',                                  'nvarchar(max)', 'NULL', nil ],
      [ 'original_ref2',                                                'original_ref2',                                                'nvarchar(max)', 'NULL', nil ],
      [ 'original_ref3po_number',                                       'original_ref3po_number',                                       'nvarchar(max)', 'NULL', nil ],
      [ 'original_department_reference_description',                    'original_department_reference_description',                    'nvarchar(max)', 'NULL', nil ],
      [ 'updated_customer_reference',                                   'updated_customer_reference',                                   'nvarchar(max)', 'NULL', nil ],
      [ 'updated_ref2',                                                 'updated_ref2',                                                 'nvarchar(max)', 'NULL', nil ],
      [ 'updated_ref3po_number',                                        'updated_ref3po_number',                                        'nvarchar(max)', 'NULL', nil ],
      [ 'updated_department_reference_description',                     'updated_department_reference_description',                     'nvarchar(max)', 'NULL', nil ],
      [ 'rma',                                                          'rma',                                                          'nvarchar(max)', 'NULL', nil ],
      [ 'original_recipient_address_line_1',                            'original_recipient_address_line_1',                            'nvarchar(max)', 'NULL', nil ],
      [ 'original_recipient_address_line_2',                            'original_recipient_address_line_2',                            'nvarchar(max)', 'NULL', nil ],
      [ 'original_recipient_city',                                      'original_recipient_city',                                      'nvarchar(max)', 'NULL', nil ],
      [ 'original_recipient_state',                                     'original_recipient_state',                                     'nvarchar(max)', 'NULL', nil ],
      [ 'original_recipient_zip_code',                                  'original_recipient_zip_code',                                  'nvarchar(max)', 'NULL', nil ],
      [ 'original_recipient_countryterritory',                          'original_recipient_countryterritory',                          'nvarchar(max)', 'NULL', nil ],
      [ 'zone_code',                                                    'zone_code',                                                    'nvarchar(max)', 'NULL', nil ],
      [ 'cost_allocation',                                              'cost_allocation',                                              'nvarchar(max)', 'NULL', nil ],
      [ 'alternate_address_line_1',                                     'alternate_address_line_1',                                     'nvarchar(max)', 'NULL', nil ],
      [ 'alternate_address_line_2',                                     'alternate_address_line_2',                                     'nvarchar(max)', 'NULL', nil ],
      [ 'alternate_city',                                               'alternate_city',                                               'nvarchar(max)', 'NULL', nil ],
      [ 'alternate_state_province',                                     'alternate_state_province',                                     'nvarchar(max)', 'NULL', nil ],
      [ 'alternate_zip_code',                                           'alternate_zip_code',                                           'nvarchar(max)', 'NULL', nil ],
      [ 'alternate_countryterritory_code',                              'alternate_countryterritory_code',                              'nvarchar(max)', 'NULL', nil ],
      [ 'crossreftrackingid_prefix',                                    'crossreftrackingid_prefix',                                    'nvarchar(max)', 'NULL', nil ],
      [ 'crossreftrackingid',                                           'crossreftrackingid',                                           'nvarchar(max)', 'NULL', nil ],
      [ 'entry_date',                                                   'entry_date',                                                   'nvarchar(max)', 'NULL', nil ],
      [ 'entry_number',                                                 'entry_number',                                                 'nvarchar(max)', 'NULL', nil ],
      [ 'customs_value',                                                'customs_value',                                                'nvarchar(max)', 'NULL', nil ],
      [ 'customs_value_currency_code',                                  'customs_value_currency_code',                                  'nvarchar(max)', 'NULL', nil ],
      [ 'declared_value',                                               'declared_value',                                               'nvarchar(max)', 'NULL', nil ],
      [ 'declared_value_currency_code',                                 'declared_value_currency_code',                                 'nvarchar(max)', 'NULL', nil ],
      [ 'commodity_description',                                        'commodity_description',                                        'nvarchar(max)', 'NULL', nil ],
      [ 'commodity_countryterritory_code',                              'commodity_countryterritory_code',                              'nvarchar(max)', 'NULL', nil ],
      [ 'commodity_description_2',                                      'commodity_description_2',                                      'nvarchar(max)', 'NULL', nil ],
      [ 'commodity_countryterritory_code_2',                            'commodity_countryterritory_code_2',                            'nvarchar(max)', 'NULL', nil ],
      [ 'commodity_description_3',                                      'commodity_description_3',                                      'nvarchar(max)', 'NULL', nil ],
      [ 'commodity_countryterritory_code_3',                            'commodity_countryterritory_code_3',                            'nvarchar(max)', 'NULL', nil ],
      [ 'commodity_description_4',                                      'commodity_description_4',                                      'nvarchar(max)', 'NULL', nil ],
      [ 'commodity_countryterritory_code_4',                            'commodity_countryterritory_code_4',                            'nvarchar(max)', 'NULL', nil ],
      [ 'currency_conversion_date',                                     'currency_conversion_date',                                     'nvarchar(max)', 'NULL', nil ],
      [ 'currency_conversion_rate',                                     'currency_conversion_rate',                                     'nvarchar(max)', 'NULL', nil ],
      [ 'multiweight_number',                                           'multiweight_number',                                           'nvarchar(max)', 'NULL', nil ],
      [ 'multiweight_total_multiweight_units',                          'multiweight_total_multiweight_units',                          'nvarchar(max)', 'NULL', nil ],
      [ 'multiweight_total_multiweight_weight',                         'multiweight_total_multiweight_weight',                         'nvarchar(max)', 'NULL', nil ],
      [ 'multiweight_total_shipment_charge_amount',                     'multiweight_total_shipment_charge_amount',                     'nvarchar(max)', 'NULL', nil ],
      [ 'multiweight_total_shipment_weight',                            'multiweight_total_shipment_weight',                            'nvarchar(max)', 'NULL', nil ],
      [ 'ground_tracking_id_address_correction_discount_charge_amount', 'ground_tracking_id_address_correction_discount_charge_amount', 'nvarchar(max)', 'NULL', nil ],
      [ 'ground_tracking_id_address_correction_gross_charge_amount',    'ground_tracking_id_address_correction_gross_charge_amount',    'nvarchar(max)', 'NULL', nil ],
      [ 'rated_method',                                                 'rated_method',                                                 'nvarchar(max)', 'NULL', nil ],
      [ 'sort_hub',                                                     'sort_hub',                                                     'nvarchar(max)', 'NULL', nil ],
      [ 'estimated_weight',                                             'estimated_weight',                                             'nvarchar(max)', 'NULL', nil ],
      [ 'estimated_weight_unit',                                        'estimated_weight_unit',                                        'nvarchar(max)', 'NULL', nil ],
      [ 'postal_class',                                                 'postal_class',                                                 'nvarchar(max)', 'NULL', nil ],
      [ 'process_category',                                             'process_category',                                             'nvarchar(max)', 'NULL', nil ],
      [ 'package_size',                                                 'package_size',                                                 'nvarchar(max)', 'NULL', nil ],
      [ 'delivery_confirmation',                                        'delivery_confirmation',                                        'nvarchar(max)', 'NULL', nil ],
      [ 'tendered_date',                                                'tendered_date',                                                'nvarchar(max)', 'NULL', nil ],
      [ 'mps_package_id',                                               'mps_package_id',                                               'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_description',                               'tracking_id_charge_description',                               'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_amount',                                    'tracking_id_charge_amount',                                    'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_description_2',                             'tracking_id_charge_description_2',                             'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_amount_2',                                  'tracking_id_charge_amount_2',                                  'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_description_3',                             'tracking_id_charge_description_3',                             'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_amount_3',                                  'tracking_id_charge_amount_3',                                  'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_description_4',                             'tracking_id_charge_description_4',                             'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_amount_4',                                  'tracking_id_charge_amount_4',                                  'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_description_5',                             'tracking_id_charge_description_5',                             'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_amount_5',                                  'tracking_id_charge_amount_5',                                  'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_description_6',                             'tracking_id_charge_description_6',                             'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_amount_6',                                  'tracking_id_charge_amount_6',                                  'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_description_7',                             'tracking_id_charge_description_7',                             'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_amount_7',                                  'tracking_id_charge_amount_7',                                  'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_description_8',                             'tracking_id_charge_description_8',                             'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_amount_8',                                  'tracking_id_charge_amount_8',                                  'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_description_9',                             'tracking_id_charge_description_9',                             'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_amount_9',                                  'tracking_id_charge_amount_9',                                  'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_description_10',                            'tracking_id_charge_description_10',                            'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_amount_10',                                 'tracking_id_charge_amount_10',                                 'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_description_11',                            'tracking_id_charge_description_11',                            'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_amount_11',                                 'tracking_id_charge_amount_11',                                 'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_description_12',                            'tracking_id_charge_description_12',                            'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_amount_12',                                 'tracking_id_charge_amount_12',                                 'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_description_13',                            'tracking_id_charge_description_13',                            'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_amount_13',                                 'tracking_id_charge_amount_13',                                 'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_description_14',                            'tracking_id_charge_description_14',                            'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_amount_14',                                 'tracking_id_charge_amount_14',                                 'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_description_15',                            'tracking_id_charge_description_15',                            'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_amount_15',                                 'tracking_id_charge_amount_15',                                 'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_description_16',                            'tracking_id_charge_description_16',                            'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_amount_16',                                 'tracking_id_charge_amount_16',                                 'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_description_17',                            'tracking_id_charge_description_17',                            'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_amount_17',                                 'tracking_id_charge_amount_17',                                 'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_description_18',                            'tracking_id_charge_description_18',                            'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_amount_18',                                 'tracking_id_charge_amount_18',                                 'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_description_19',                            'tracking_id_charge_description_19',                            'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_amount_19',                                 'tracking_id_charge_amount_19',                                 'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_description_20',                            'tracking_id_charge_description_20',                            'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_amount_20',                                 'tracking_id_charge_amount_20',                                 'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_description_21',                            'tracking_id_charge_description_21',                            'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_amount_21',                                 'tracking_id_charge_amount_21',                                 'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_description_22',                            'tracking_id_charge_description_22',                            'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_amount_22',                                 'tracking_id_charge_amount_22',                                 'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_description_23',                            'tracking_id_charge_description_23',                            'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_amount_23',                                 'tracking_id_charge_amount_23',                                 'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_description_24',                            'tracking_id_charge_description_24',                            'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_amount_24',                                 'tracking_id_charge_amount_24',                                 'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_description_25',                            'tracking_id_charge_description_25',                            'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_amount_25',                                 'tracking_id_charge_amount_25',                                 'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_description_26',                            'tracking_id_charge_description_26',                            'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_amount_26',                                 'tracking_id_charge_amount_26',                                 'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_description_27',                            'tracking_id_charge_description_27',                            'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_amount_27',                                 'tracking_id_charge_amount_27',                                 'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_description_28',                            'tracking_id_charge_description_28',                            'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_amount_28',                                 'tracking_id_charge_amount_28',                                 'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_description_29',                            'tracking_id_charge_description_29',                            'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_amount_29',                                 'tracking_id_charge_amount_29',                                 'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_description_30',                            'tracking_id_charge_description_30',                            'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_amount_30',                                 'tracking_id_charge_amount_30',                                 'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_description_31',                            'tracking_id_charge_description_31',                            'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_amount_31',                                 'tracking_id_charge_amount_31',                                 'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_description_32',                            'tracking_id_charge_description_32',                            'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_amount_32',                                 'tracking_id_charge_amount_32',                                 'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_description_33',                            'tracking_id_charge_description_33',                            'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_amount_33',                                 'tracking_id_charge_amount_33',                                 'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_description_34',                            'tracking_id_charge_description_34',                            'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_amount_34',                                 'tracking_id_charge_amount_34',                                 'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_description_35',                            'tracking_id_charge_description_35',                            'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_amount_35',                                 'tracking_id_charge_amount_35',                                 'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_description_36',                            'tracking_id_charge_description_36',                            'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_amount_36',                                 'tracking_id_charge_amount_36',                                 'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_description_37',                            'tracking_id_charge_description_37',                            'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_amount_37',                                 'tracking_id_charge_amount_37',                                 'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_description_38',                            'tracking_id_charge_description_38',                            'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_amount_38',                                 'tracking_id_charge_amount_38',                                 'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_description_39',                            'tracking_id_charge_description_39',                            'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_amount_39',                                 'tracking_id_charge_amount_39',                                 'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_description_40',                            'tracking_id_charge_description_40',                            'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_amount_40',                                 'tracking_id_charge_amount_40',                                 'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_description_41',                            'tracking_id_charge_description_41',                            'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_amount_41',                                 'tracking_id_charge_amount_41',                                 'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_description_42',                            'tracking_id_charge_description_42',                            'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_amount_42',                                 'tracking_id_charge_amount_42',                                 'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_description_43',                            'tracking_id_charge_description_43',                            'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_amount_43',                                 'tracking_id_charge_amount_43',                                 'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_description_44',                            'tracking_id_charge_description_44',                            'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_amount_44',                                 'tracking_id_charge_amount_44',                                 'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_description_45',                            'tracking_id_charge_description_45',                            'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_amount_45',                                 'tracking_id_charge_amount_45',                                 'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_description_46',                            'tracking_id_charge_description_46',                            'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_amount_46',                                 'tracking_id_charge_amount_46',                                 'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_description_47',                            'tracking_id_charge_description_47',                            'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_amount_47',                                 'tracking_id_charge_amount_47',                                 'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_description_48',                            'tracking_id_charge_description_48',                            'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_amount_48',                                 'tracking_id_charge_amount_48',                                 'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_description_49',                            'tracking_id_charge_description_49',                            'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_amount_49',                                 'tracking_id_charge_amount_49',                                 'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_description_50',                            'tracking_id_charge_description_50',                            'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_amount_50',                                 'tracking_id_charge_amount_50',                                 'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_description_51',                            'tracking_id_charge_description_51',                            'nvarchar(max)', 'NULL', nil ],
      [ 'tracking_id_charge_amount_51',                                 'tracking_id_charge_amount_51',                                 'nvarchar(max)', 'NULL', nil ],
      [ 'shipment_notes',                                               'shipment_notes',                                               'nvarchar(max)', 'NULL', nil ]

    ],
    database_connections: [
      {
        host: 'GSASQL16',
        database: 'GSABSS',
        schema: 'dbo',
        table: 'fedex',
        inject: {
          mode: :truncate_insert
        }
      }
    ]
  }
]
