inherit_from: .rubocop_todo.yml
inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.0
  UseCache: false

Layout/LineLength:
  Max: 183

Layout/ExtraSpacing:
  Enabled: false

Metrics/AbcSize:
  Max: 67
  Exclude:
    - 'app/controllers/forms/**/*_controller.rb'

Metrics/BlockLength:
  Max: 107

Metrics/CyclomaticComplexity:
  Max: 16
  Exclude:
    - 'app/controllers/forms/**/*_controller.rb'

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/forms/**/*_controller.rb'
    - 'app/services/navigation_catalog.rb'
    - 'app/models/forms/field.rb'
    - 'app/models/forms/template.rb'
    - 'app/models/forms/template_routing_step.rb'
    - 'app/services/forms/inbox_query.rb'
    - 'app/services/form_lookup.rb'

Metrics/MethodLength:
  Max: 44
  Exclude:
    - 'app/controllers/forms/**/*_controller.rb'

Metrics/ModuleLength:
  Max: 146

Metrics/ParameterLists:
  Max: 8

Metrics/PerceivedComplexity:
  Max: 14
  Exclude:
    - 'app/controllers/forms/**/*_controller.rb'
    - 'app/models/forms/template_routing_step.rb'

Style/MultilineBlockChain:
  Exclude:
    - 'app/models/forms/template_routing_step.rb'

Naming/MethodParameterName:
  MinNameLength: 1

Style/Documentation:
  Enabled: false
