AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.0
  UseCache: false

Layout/LineLength:
  Max: 183

Lint/RedundantCopDisableDirective:
  Enabled: false

Metrics/AbcSize:
  Max: 67

Metrics/BlockLength:
  Max: 107

Metrics/CyclomaticComplexity:
  Max: 16

Metrics/MethodLength:
  Max: 44

Metrics/ModuleLength:
  Max: 146

Metrics/ParameterLists:
  Max: 8

Metrics/PerceivedComplexity:
  Max: 14

Naming/MethodParameterName:
  MinNameLength: 1

Naming/PredicateMethod:
  Enabled: false

Naming/PredicatePrefix:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false
