#!/usr/bin/env bash

source stopservers
stop_servers
{
  bundle check || bundle install
  bundle exec bin/rails assets:clobber
  bundle exec bin/rails assets:precompile
} 2>&1 | tee assets.log

nohup bundle exec bin/rails server -p 3001 </dev/null >server.log 2>&1 &
nohup bundle exec sidekiq -C config/sidekiq.yml </dev/null >sidekick.log 2>&1 &
