#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")"

bundle check || bundle install
bundle exec bin/rails assets:clobber
bundle exec bin/rails assets:precompile
exec bundle exec bin/rails server -p 3001
