# frozen_string_literal: true

require 'dotenv/load'
require 'pathname'

module P2m
  module Paths
    DATA_RUNNER_ROOT = ENV.fetch('P2M_DATARUNNER_ROOT')
    SENT_TO_USPS = ENV.fetch('P2M_SENT_TO_USPS')
    SHIPPING_STATION = ENV.fetch('P2M_SHIPPING_STATION')
    TEMPORARY_OUTPUT = ENV.fetch('P2M_TEMPORARY_OUTPUT')
    PROCESSED = ENV.fetch('P2M_PROCESSED')

    STAGING_PATH = DATA_RUNNER_ROOT.join(SENT_TO_USPS)
    SHIPPING_STATION_PATH = DATA_RUNNER_ROOT.join(SHIPPING_STATION)
    PROCESSED_PATH = DATA_RUNNER_ROOT.join(PROCESSED)
  end
end
