class AddDisplayNameAndAutoGeneratedToRoutingStepsAndStatuses < ActiveRecord::Migration[7.1]
  def change
    add_column :form_template_routing_steps, :display_name, :string
    add_column :form_template_statuses, :auto_generated, :boolean, default: false
  end
end
